spring:
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            cors-configurations:
                '[/**]':
#                    allowed-origins:
#                      - "http://localhost:4200"
                    allowed-origins: "*"
                    allowed-methods: "*"
                    allowed-headers: "*"
