spring.application.name=ebank-service
server.port=8083
spring.cloud.discovery.enabled=true
spring.config.import=optional:configserver:http://localhost:9999
spring.datasource.url=jdbc:mysql://localhost:3306/E_Bank?createDatabaseIfNotExist=true
spring.jpa.hibernate.ddl-auto = create
spring.datasource.username=nada
spring.datasource.password=essat
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true