spring.application.name=chat-service
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3
server.port=8058
spring.cloud.config.enabled=false
spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp 
#adress de mcp server c a dire au démarrage va chercher les tools ici
