spring.application.name=chat-service

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1

server.port=8058
spring.cloud.config.enabled=false
spring.ai.mcp.client.streamable-http.connections.customer.url=http://localhost:8081/mcp8081/mcp